# Configuration for ANN spatial model - OPTIMIZED FOR SPATIAL TASKS

# Extend default configuration
defaults:
  - ../default

# Override settings for spatial ANN model
model:
  model_type: "spatial"
  activation: "relu"

# Hyperparameters SPECIALIZED FOR GEOMETRIC PATTERN RECOGNITION
hyperparameters:
  batch_size: 64  # Moderate batch size for better generalization on geometric patterns
  hidden_size: 512  # Very large capacity for complex pattern detection
  dropout_rate: 0.1  # Low dropout for maximum pattern learning

# Optimizer settings - specifically tuned for geometric shapes in small_spatial_10class
optimizer:
  optimizer_choice: "Adam"
  Adam:
    lr: 0.001  # Learning rate consistent with what's actually being used in batch_compare.py
    weight_decay: 1e-6  # Minimal regularization to learn exact shape boundaries

# Scheduler settings - more gradual learning rate decay
scheduler:
  scheduler_choice: "MultiStepLR"  # More predictable than cosine annealing
  MultiStepLR:
    milestones: [10, 20, 30]  # Decay points
    gamma: 0.5  # Moderate decay factor
