# Configuration for ANN synthetic model

# Extend default configuration
defaults:
  - ../default

# Override settings for synthetic ANN model
model:
  model_type: "synthetic"
  activation: "relu"

# Hyperparameters for ANN with extreme anti-overfitting measures
hyperparameters:
  batch_size: 24  # Further reduced batch size for better generalization
  hidden_size: 64  # Significantly reduced model capacity to prevent overfitting
  dropout_rate: 0.5  # Maximized dropout to prevent overfitting
  epoch: 50  # Increased epochs to accommodate harder datasets
  early_stop_patience: 7  # Increased patience to allow more exploration on difficult datasets

# Optimizer settings for quick initial convergence
optimizer:
  optimizer_choice: "Adam"
  Adam:
    lr: 0.001  # Increased learning rate for faster initial convergence
    weight_decay: 0.005  # Substantially increased weight decay for extreme regularization
    amsgrad: true
    eps: 1e-8

# Scheduler optimized for early performance
scheduler:
  scheduler_choice: "OneCycleLR"  # Change to OneCycleLR for better early performance
  OneCycleLR:
    max_lr: 0.002
    pct_start: 0.2  # Peak early at 20% of training
    div_factor: 10.0
    final_div_factor: 100.0
