# Configuration for ANN synthetic model

# Extend default configuration
defaults:
  - ../default

# Override settings for synthetic ANN model
model:
  model_type: "synthetic"
  activation: "relu"

# Hyperparameters for ANN (no spike-specific params needed)
hyperparameters:
  batch_size: 32
  hidden_size: 128  # Can use larger hidden size for ANN
  dropout_rate: 0.3

# Optimizer settings optimized for ANN
optimizer:
  optimizer_choice: "Adam"
  Adam:
    lr: 0.001

# Scheduler settings
scheduler:
  scheduler_choice: "MultiStepLR"
  MultiStepLR:
    milestones: [20, 40]
    gamma: 0.1
