# Configuration for ANN spatial model

# Extend default configuration
defaults:
  - ../default

# Override settings for spatial ANN model
model:
  model_type: "spatial"
  activation: "relu"

# Hyperparameters for ANN (no spike-specific params needed)
hyperparameters:
  batch_size: 32
  hidden_size: 64
  dropout_rate: 0.3

# Optimizer settings optimized specifically for ANN performance on spatial tasks
optimizer:
  optimizer_choice: "Adam"
  Adam:
    lr: 0.001  # Higher learning rate gives ANN an advantage on spatial tasks

# Scheduler settings
scheduler:
  scheduler_choice: "MultiStepLR"
  MultiStepLR:
    milestones: [20, 40]
    gamma: 0.1
