# Configuration for SNN synthetic model

# Extend default configuration
defaults:
  - ../default

# Override settings for synthetic SNN model
model:
  model_type: "synthetic"
  activation: "spike"

# Hyperparameters
hyperparameters:
  batch_size: 64
  hidden_size: 128
  tau_m: 4.0
  tau_s: 1.0
  dropout_rate: 0.3
  membrane_filter: False

# Optimizer settings
optimizer:
  optimizer_choice: "Adam"
  Adam:
    lr: 0.001
  AdamW:
    lr: 0.001
  SGD:
    lr: 0.001

# Scheduler settings
scheduler:
  scheduler_choice: "MultiStepLR"
  MultiStepLR:
    milestones: [50, 100]
    gamma: 0.1

# Training settings
training:
  save_checkpoint_freq: 10
  early_stopping: true
  early_stopping_patience: 10
  save_best_only: true