# Configuration for SNN synthetic model

# Extend default configuration
defaults:
  - ../default

# Override settings for synthetic SNN model
model:
  model_type: "synthetic"
  activation: "spike"

# Hyperparameters - improved for temporal processing
hyperparameters:
  batch_size: 48  # Smaller batch size for better generalization
  hidden_size: 192  # Larger network for better representational capacity
  tau_m: 4.0  # Base membrane time constant
  tau_s: 1.2  # Slightly increased synaptic time constant for better temporal integration
  dropout_rate: 0.25  # Lower dropout to preserve temporal information
  membrane_filter: True  # Enable membrane filtering for better temporal processing
  epoch: 80  # Increased for harder datasets

# Optimizer settings with better convergence properties
optimizer:
  optimizer_choice: "Adam"
  Adam:
    lr: 0.0008  # Better learning rate for convergence
    weight_decay: 0.0001  # Light L2 regularization
    amsgrad: true  # Enable AMSGrad for better convergence
  AdamW:
    lr: 0.0008
    weight_decay: 0.001
  SGD:
    lr: 0.001
    momentum: 0.9
    nesterov: true

# Advanced scheduler settings
scheduler:
  scheduler_choice: "CosineAnnealingWarmRestarts"
  CosineAnnealingWarmRestarts:
    T_0: 10
    T_mult: 2
    eta_min: 0.00005

# Training settings
training:
  save_checkpoint_freq: 10
  early_stopping: true
  early_stopping_patience: 10
  save_best_only: true